# Current Time: 2025-05-31 05:59:35
# Current User: EuniceNzilani

name: visits_tracker
description: A Route-to-Market Sales Force Automation app with visit tracking capabilities.
version: 1.0.0+1

environment:
  sdk: '^3.7.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.0.0
  
  # Networking
  dio: ^4.0.0
  
  # Data Handling
  json_annotation: ^4.0.0
  shared_preferences: ^2.0.0
  intl: ^0.17.0
  
  # Core Dependencies
  meta: ^1.9.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Code Generation
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  
  # Testing
  bloc_test: ^9.0.0
  mockito: ^5.0.0
  
  # Linting
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300